# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
source "$ZSH/oh-my-zsh.sh"

# Core environment
export LDFLAGS="-L$(brew --prefix libyaml)/lib"
export CPPFLAGS="-I$(brew --prefix libyaml)/include"
export RUBY_YJIT_ENABLE=1
export RUBY_CONFIGURE_OPTS=--enable-yjit
export EDITOR="zed"
export VISUAL="zed"
export BUN_INSTALL="$HOME/.bun"
export PGGSSENCMODE="disable"

# PATH
export PATH="$HOME/.local/bin:$PATH"
export PATH="/opt/homebrew/opt/postgresql@18/bin:$PATH"
export PATH="$BUN_INSTALL/bin:$PATH"

# Interactive shell tooling
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(mise activate zsh)"
eval "$(fzf --zsh)"

# Completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
